### ISSUE TITLE
Tag managment

### ISSUE THREAD

**Issue by arthurTemporim** [andre-filho/commit-helper#77]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Is there any plan to make this solution bigger? Like managing releases with templates and tags in the terminal?

In a longer future, is there any plan to make this project, even more, smarter, like to make it manage issues, PRs and anything in GitHub and/or GitLab?

**Describe alternatives you've considered**
I started a project to help mainly in tag management and things like this, if you are not planning to do it please, let me know :D

**Additional context**
Congratulations to the project, every piece of it are just awesome!

**Comment by andre-filho** [comment]
Thanks @arthurTemporim, in the moment I have no plans in taking **this** project into the realm of git tag management nor into PRs and issue management. This is another idea that I've had and hasn't started to develop yet. (If you want to talk about this idea in person, maybe it would benefit us both, idk).

The commit-helper utility was meant to help developers in the process of writing git commits in a fast  manner even when following commit conventions, while keeping the flow simple. I usually write down the next steps of this project in my release notes or in issues, like the issue #75. In that issue is described my plans for the next version of this tool.

Good luck in your project btw :+1:

**Comment by arthurTemporim** [comment]
Sure, I saw the releases and it is very documented, all the project is very good, again, **congratulations**! Maybe we can start with the `tag` feature and plan about more features that can benefit us both as you said. Thanks!
